# Generated by Django 4.0.1 on 2022-04-20 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('supplier_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('supplier_name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='supplied',
            fields=[
                ('supplied_pk', models.AutoField(primary_key=True, serialize=False)),
                ('supplied_qnt', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
    ]
